In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df=pd.read_csv("/home/nmietcomp/Downloads/Student_Performance_Database/xAPI-Edu-Data.csv")

In [18]:
df

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,16.0,yes,good,under-7,m,NaN,NaN,NaN
1,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,20.0,20,3,25,yes,good,under-7,m
2,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,10.0,30,no,bad,above-7,l,NaN,NaN
3,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,30.0,25,5,35,no,bad,above-7,l
4,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,40.0,50,12,50,no,bad,above-7,m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,f,jordan,jordan,middleschool,g-08,a,chemistry,s,father,5.0,4,5,8,no,bad,above-7,l
476,f,jordan,jordan,middleschool,g-08,a,geology,f,father,50.0,77,14,28,no,bad,under-7,m
477,f,jordan,jordan,middleschool,g-08,a,geology,s,father,55.0,74,25,29,no,bad,under-7,m
478,f,jordan,jordan,middleschool,g-08,a,history,f,father,30.0,17,14,57,no,bad,above-7,l
479,f,jordan,jordan,middleschool,g-08,a,history,s,father,35.0,14,23,62,no,bad,above-7,l

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    480 non-null    object
 1   NationalITy               480 non-null    object
 2   PlaceofBirth              480 non-null    object
 3   StageID                   480 non-null    object
 4   GradeID                   479 non-null    object
 5   SectionID                 479 non-null    object
 6   Topic                     479 non-null    object
 7   Semester                  479 non-null    object
 8   Relation                  479 non-null    object
 9   raisedhands               478 non-null    float64
 10  VisITedResources          478 non-null    object
 11  AnnouncementsView         478 non-null    object
 12  Discussion                478 non-null    object
 13  ParentAnsweringSurvey     478 non-null    object
 14  ParentschoolSatisfaction  477 non-null    object
 15  StudentAbsenceDays        476 non-null    object
 16  Class                     474 non-null    object
dtypes: float64(1), object(16)
memory usage: 63.9+ KB

In [21]:
df.isnull().sum()

gender                      0
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     1
SectionID                   1
Topic                       1
Semester                    1
Relation                    1
raisedhands                 2
VisITedResources            2
AnnouncementsView           2
Discussion                  2
ParentAnsweringSurvey       2
ParentschoolSatisfaction    3
StudentAbsenceDays          4
Class                       6
dtype: int64

In [14]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"\n{col} unique values:")
    print(df[col].unique())

gender unique values:
['M' 'F']

NationalITy unique values:
['KW' 'lebanon' 'Egypt' 'SaudiArabia' 'USA' 'Jordan' 'venzuela' 'Iran'
 'Tunis' 'Morocco' 'Syria' 'Palestine' 'Iraq' 'Lybia']

PlaceofBirth unique values:
['KuwaIT' 'lebanon' 'Egypt' 'SaudiArabia' 'USA' 'Jordan' 'venzuela' 'Iran'
 'Tunis' 'Morocco' 'Syria' 'Iraq' 'Palestine' 'Lybia']

StageID unique values:
['lowerlevel' 'MiddleSchool' 'HighSchool']

GradeID unique values:
['G-04' 'G-07' 'G-08' 'G-06' 'G-05' nan 'G-09' 'G-12' 'G-11' 'Math' 'G-10'
 'G-02']

SectionID unique values:
['A' 'B' nan 'F' 'C']

Topic unique values:
['IT' 'Math' 'Arabic' 'Science' 'English' nan 'Quran' 'Father' 'Spanish'
 'French' 'History' 'Biology' 'Chemistry' 'Geology']

Semester unique values:
['F' nan 'Under-7' 'S']

Relation unique values:
['Father' 'Mum' nan 'M']

VisITedResources unique values:
['Yes' '20' '30' '25' '50' '12' '10' '21' '80' '88' '6' '1' '14' '70' '40'
 '13' '15' '60' '0' '2' '7' '19' '85' '90' '5' '22' '11' '54' nan '35'
 '33' '4' '39' '75' '69' '3' '8' '89' '44' '92' '26' '27' '29' '98' '9'
 '42' '65' '79' '55' '63' '91' '51' '58' '68' '82' '72' '52' '62' '71'
 '66' '43' '95' '31' '41' '81' '61' '83' '84' '17' '94' '48' '86' '74'
 '76' '97' '87' '99' '34' '64' '28' '38' '36' '24' '59' '57' '77' '18'
 '93' '96' '78']

AnnouncementsView unique values:
['Good' '3' 'No' '5' '12' '13' '0' '15' '16' '25' '30' '19' '44' '22' '20'
 '35' '36' '40' '33' '4' '2' '52' '50' '10' '9' '8' '17' '26' '37' nan
 '28' '1' '39' '6' '32' '70' '7' '18' '23' '11' '29' '49' '55' '38' '41'
 '51' '95' '85' '71' '98' '73' '48' '58' '93' '83' '53' '63' '62' '82'
 '72' '42' '46' '77' '21' '88' '66' '86' '80' '56' '91' '65' '76' '24'
 '74' '59' '79' '34' '69' '89' '31' '60' '54' '57' '64' '87' '75' '67'
 '43' '45' '14' '78']

Discussion unique values:
['Under-7' '25' 'Bad' '35' '50' '70' '17' '22' 'Yes' '80' '12' '11' '19'
 '60' '66' '90' '96' '99' '40' '33' '43' '16' '30' '4' nan '88' '77' '75'
 '20' '1' '5' '2' '8' '13' '44' '9' '55' '10' '15' '7' '3' '14' '69' '59'
 '89' '41' '91' '49' '73' '23' '53' '93' '51' '83' '24' '84' '61' '94'
 '34' '81' '29' '46' '26' '6' '76' '86' '85' '65' '95' '64' '32' '37' '36'
 '27' '39' '74' '79' '21' '31' '28' '38' '48' '97' '98' '63' '72' '82'
 '71' '45' '68' '92' '58' '57' '62']

ParentAnsweringSurvey unique values:
['M' 'Yes' 'Above-7' 'No' 'Good' nan]

ParentschoolSatisfaction unique values:
[nan 'Good' 'L' 'Bad' 'Under-7']

StudentAbsenceDays unique values:
[nan 'Under-7' 'Above-7' 'M']

Class unique values:
[nan 'M' 'L' 'H']

In [19]:
df

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,15,16,2,20,yes,good,under-7,m
1,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,20,20,3,25,yes,good,under-7,m
2,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,10,7,0,30,no,bad,above-7,l
3,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,30,25,5,35,no,bad,above-7,l
4,m,kw,kuwait,lowerlevel,g-04,a,it,f,father,40,50,12,50,no,bad,above-7,m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,f,jordan,jordan,middleschool,g-08,a,chemistry,s,father,5,4,5,8,no,bad,above-7,l
476,f,jordan,jordan,middleschool,g-08,a,geology,f,father,50,77,14,28,no,bad,under-7,m
477,f,jordan,jordan,middleschool,g-08,a,geology,s,father,55,74,25,29,no,bad,under-7,m
478,f,jordan,jordan,middleschool,g-08,a,history,f,father,30,17,14,57,no,bad,above-7,l
479,f,jordan,jordan,middleschool,g-08,a,history,s,father,35,14,23,62,no,bad,above-7,l